apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: project-manager-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-manager-frontend
  template:
    metadata:
      labels:
        app: project-manager-frontend
    spec:
      containers:
        - name: project-manager-frontend
          image: carloshot007/project-manager-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: project-manager-frontend
