services:
  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  task_manager:
    image: br4z/task_manager-backend # br4z/task_manager-backend
    environment:
      PORT: 8000
      DB_HOST: postgresql:5432
      DB_DATABASE: task_manager
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - postgresql
    ports:
      - "8000:8000"