apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-manager-backend-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /logs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-manager-backend-pvc
spec:
  volumeName: task-manager-backend-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
