apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-backend
  template:
    metadata:
      labels:
        app: task-manager-backend
    spec:
      containers:
      - name: task-manager-backend
        image: br4z/task_manager-backend
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: task-manager-backend
                key: PORT
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: task-manager-backend
                key: DB_HOST
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: task-manager-backend
                key: DB_DATABASE
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: task-manager-backend
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: task-manager-backend
                key: DB_PASSWORD
        volumeMounts:
        - mountPath: /usr/app/logs
          name: logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: task-manager-backend-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend
spec:
  type: ClusterIP
  selector:
    app: task-manager-backend
  ports:
  - port: 80
    targetPort: 8000
