server:
  port: ${DB_PORT}

loggin:
  level:
    com.task_manager.app=INFO
  file.name: logs/spring-boot-logging.log

spring:
  application:
    name: task_manager
  datasource:
    name: ${DB_DATABASE}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  h2.console.enabled: false

