server:
  port: 8000

logging:
  level:
    com.task_manager.app=INFO
  file.name: logs/spring-boot-logging.log

spring:
  application:
    name: task_manager
  datasource:
    name: task_manager
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-ui
